// Copyright © 2023 Mike Brown; see LICENSE at the root of this package

using System.IO;
using System.Text;

namespace CGSM;

public class ClusterYamlEmitter {
    private string outputFile;
    private Cluster cluster;
    private int category;

    // @todo does c# have the equivalent of go:embed ?
    private static string ClusterYamlHeaderTextFmt = @"name: STRINGS.CLUSTER_NAMES.CGSM_CLUSTER.NAME
description: STRINGS.CLUSTER_NAMES.CGSM_CLUSTER.DESCRIPTION
requiredDlcIds: [{5}]
coordinatePrefix: CGSM-C
menuOrder: {4}
clusterCategory: {0}
{1}difficulty: {2}

{6}startWorldIndex: {3}
";

    public ClusterYamlEmitter(Cluster clusterIn, int categoryIn, string outputFileIn) {
        this.cluster = clusterIn;
        this.outputFile = outputFileIn;
        this.category = categoryIn;
    }

    /* returns whether or not the generated yaml has changed */
    public bool emit() {
        StringBuilder yamlContent = new StringBuilder();

        emitHeaders(ref yamlContent);
        if (this.cluster.placePriority == Cluster.PlacePriority.Start) {
            emitStartPlanet(ref yamlContent);
            emitWarpPlanet(ref yamlContent);
            emitOtherPlanets(ref yamlContent, false);
        } else if (this.cluster.placePriority == Cluster.PlacePriority.Warp) {
            emitWarpPlanet(ref yamlContent);
            emitStartPlanet(ref yamlContent);
            emitOtherPlanets(ref yamlContent, false);
        } else {
            // Cluster.PlacePriority.FirstOther
            emitFirstOtherPlanet(ref yamlContent);
            emitStartPlanet(ref yamlContent);
            emitWarpPlanet(ref yamlContent);
            emitOtherPlanets(ref yamlContent, true);
        }
        emitSpacePOIs(ref yamlContent);

        if (File.Exists(this.outputFile)) {
            var existingyamlContent = File.ReadAllText(this.outputFile);
            if (existingyamlContent == yamlContent.ToString()) {
                // Util.LogDbg("Skipping write of {0}", this.outputFile);
                return false;
            }
        }

        // Util.LogDbg("Generating {0} from {1}", this.outputFile, this.cluster);
        // Util.LogDbg("Generated yaml file content is: {0}", yamlContent.ToString());

        File.WriteAllText(this.outputFile, yamlContent.ToString());

        return true;
    }

    private void emitHeaders(ref StringBuilder yamlContent) {
        var storyTraitsStr = "disableStoryTraits: true\n";
        if (this.cluster.storyTraits) {
            storyTraitsStr = "";
        }

        // DLC4 clusters (Prehistoric) have extra cluster metadata to enable the
        // Demolior/Prehistoric content and audio.
        var dlc4HeaderExtras = "";
        if (this.cluster?.start?.planetoid?.RequiredDlcIdToken() == "DLC4_ID") {
            dlc4HeaderExtras =
                "clusterTags:\n" +
                "- PrehistoricCluster\n" +
                "- DemoliorImperative\n\n" +
                "clusterAudio:\n" +
                "  musicWelcome: Music_WattsonMessage_DLC4\n" +
                "  musicFirst: Prehistoric_Planet\n" +
                "  stingerDay: Stinger_Day_DLC4\n" +
                "  stingerNight: Stinger_Loop_Night_DLC4\n\n";
        }

        int startWorldIndex = 0;
        if (this.cluster.placePriority != Cluster.PlacePriority.Start) {
            startWorldIndex = 1;
        }
        yamlContent.Append(string.Format("# AUTOGENERATED by CGSM v{0}\n", Util.Version()));

        // Always require EXPANSION1. Also require DLC2/DLC4 if any planetoids in this cluster
        // are from those DLCs.
        var requiredDlcIds = new StringBuilder();
        requiredDlcIds.Append("EXPANSION1_ID");

        bool needsDlc2 = false;
        bool needsDlc4 = false;

        void ConsiderPlanetoid(PlanetoidPlacement placement) {
            if (placement?.planetoid == null)
                return;
            var token = placement.planetoid.RequiredDlcIdToken();
            if (token == "DLC2_ID") {
                needsDlc2 = true;
            } else if (token == "DLC4_ID") {
                needsDlc4 = true;
            }
        }

        // Some clusters may not include any DLC2/DLC4 planetoids, but can still include
        // DLC-specific HarvestableSpacePOI.
        void ConsiderPOI(POIType poi) {
            if (poi == POIType.DLC2CeresOreField) {
                needsDlc2 = true;
            } else if (poi == POIType.DLC4PrehistoricOreField) {
                needsDlc4 = true;
            }
        }

        ConsiderPlanetoid(this.cluster.start);
        ConsiderPlanetoid(this.cluster.warp);
        foreach (var placement in this.cluster.others) {
            ConsiderPlanetoid(placement);
        }

        foreach (var poiGroup in this.cluster.poiGroups) {
            foreach (var poi in poiGroup.poiList) {
                ConsiderPOI(poi);
            }
        }

        if (needsDlc2) {
            requiredDlcIds.Append(", DLC2_ID");
        }
        if (needsDlc4) {
            requiredDlcIds.Append(", DLC4_ID");
        }

        yamlContent.Append(string.Format(ClusterYamlHeaderTextFmt, this.category, storyTraitsStr,
                                             this.cluster.difficulty, startWorldIndex, -16,
                                             requiredDlcIds.ToString(), dlc4HeaderExtras));
        yamlContent.Append(string.Format("numRings: {0}\nworldPlacements:\n",
                                         this.cluster.radius));
    }

    private void emitStartPlanet(ref StringBuilder yamlContent) {
        yamlContent.Append(this.cluster.start.ToYamlString());
    }

    private void emitWarpPlanet(ref StringBuilder yamlContent) {
        yamlContent.Append(this.cluster.warp.ToYamlString());
    }

    private void emitOtherPlanets(ref StringBuilder yamlContent, bool skipFirst) {
        bool didSkip = false;
        foreach (var placement in this.cluster.others) {
            if (skipFirst && !didSkip) {
                didSkip = true;
                continue;
            }
            yamlContent.Append(placement.ToYamlString());
        }
    }

    private void emitFirstOtherPlanet(ref StringBuilder yamlContent) {
        foreach (var placement in this.cluster.others) {
            yamlContent.Append(placement.ToYamlString());
            break;
        }
    }

    private void emitSpacePOIs(ref StringBuilder yamlContent) {
        if (this.cluster.poiGroups.Count == 0) {
            return;
        }

        yamlContent.Append("\npoiPlacements:\n");

        foreach (var poiGroup in this.cluster.poiGroups) {
            yamlContent.Append(poiGroup.ToYamlString());
        }
    }
}
