name: STRINGS.WORLDS.METALHEAVYLANDINGSITE.NAME
description: STRINGS.WORLDS.METALHEAVYLANDINGSITE.DESCRIPTION
forbiddenClusterTags: []
icon: asteroid_swamp_rocket_kanim
world: expansion1::worlds/MetalHeavyLandingSite
